on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: macos-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.calebvandermaas.com
        username: github@dopelab.com
        password: ${{ secrets.FTP_DEPLOY_SECRET }}
        server-dir: /calebvandermaas.com/
